name: Reusable workflow
on:
    workflow_call:
        inputs:
            who-to-greet:
                description: 'Person to greet'
                type: string
                required: true
                default: 'World'
        outputs:
            current-time:
                description: 'The time we greeted the person'
                value: ${{ jobs.reusable-job.current-time }}


jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:    
        current-time: steps.time.outputs.current-time
    steps:
    - name: checkout action repository
      uses: actions/checkout@v2    
    - name: Echo greeting
      run: echo "Hello ${{ github.events.inputs.who-to-greet }}"
    - name: Set current time
      id: time
      run: |
        echo "::set-output name=current-time::$(date)"

        