name: Reuse other workflow
on:
    workflow_dispatch:
jobs:
    call-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Call reusable workflow
              uses: ./.github/workflows/reusable.yml
              with:
                  who-to-greet: ${{ github.actor }}
    use-output:
        runs-on: ubuntu-latest
        needs: call-workflow
        steps:
        - run: echo "The time we greeted Alice was ${{ needs.call-workflow.outputs.current-time }}"             
